services:
  justtap-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: justtap-chatbot-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: justtap-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
